services:
  mms-ws:
    build: .
    networks:
      - eurekadiscoveryserver_mms-network
    ports:
      - "8080:8080"

  mms-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd1234
    networks:
      - eurekadiscoveryserver_mms-network
    ports:
      - "5442:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data

networks:
  eurekadiscoveryserver_mms-network:
    external: true

volumes:
  db-volume: